name: Android CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date + '%Y-%m-%d')"
        
      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace
      
      - run: './gradlew assembleRelease'
      - uses: MeilCli/slack-upload-file@v1
        with: 
          slack_token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL_DEPLOY }}
          file_path: 'app/build/outputs/apk/release/app-release-unsigned.apk'
          file_name: 'app-release-unsigned.apk'
          file_type: 'apk'
          initial_comment: '${{ github.ref }} 테스트 앱 .apk 배포'
      
      - name: 테스트용 apk artifact 업로드
        uses: actions/upload-artifact@v2
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
        
